server:
  servlet:
    context-path: /sicredi

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    br.com.sicredi: ${LOG_LEVEL:DEBUG}